### ISSUE TITLE
`clone_root` in `content.json` is undocumented.

### ISSUE THREAD

**Issue by weakish** [HelloZeroNet/Documentation#42]
Is this for ZeroNet's internal usage only?

**Comment by HelloZeroNet** [comment]
It's only for future use cases and not used in any way yet.

Since Rev1785 it's also possible to clone a new site from a site directory (ZeroHello > Create new, empty site does this), clone_root record this directory. It could allow easy update the cloned site from the clone source in the future.

I have update the docs: https://github.com/HelloZeroNet/Documentation/commit/3338b6130405d85ab25563b6acfb023b99123f34
